/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.ReplacementTestSuite;
	import flexUnitTests.ReplacerLogicTester;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_ReplacerLogicTester_obj:flexUnitTests.ReplacerLogicTester;
		
		private var flexUnitTests_ReplacementTestSuite_obj:flexUnitTests.ReplacementTestSuite;
	}
}